# Site settings
name: Test
email: bigheiniu@gmail.com
author: Big heiniu
url: https://bigheiniu.github.io/
#resume_site: http://www.hifreud.com/Resume.io/ 个人简历网站
github: https://github.com/bigheiniu
baseurl: ''
description: 这是一个描述!
meta_description: 哈哈
motto: I am the fattest.
banner: 爸爸吧
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bigheiniu
highlighter: Pygments

# Build settings
markdown: kramdown
# gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


FB:
  comments :
    provider : duoshuo
    duoshuo: 
        short_name : bigheiniu
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
